export default {
  POST_LIST_UPDATE: 100,
  POST_LIST_TAG_UPDATE: 101,

  POST_LIST_CATEGORY_EVENT: 'POST_LIST_CATEGORY_EVENT',
  POST_LIST_NEW_EVENT: 'POST_LIST_NEW_EVENT',
  POST_LIST_TOP_EVENT: 'POST_LIST_TOP_EVENT',
  POST_LIST_TAG_EVENT: 'POST_LIST_TAG_EVENT'
};
