export default {
  ROUTE_UPDATE_PATH: 1,
  ROUTE_AUTH_PAGE: 2,
  ROUTE_MAP_PAGE: 3,
  ROUTE_POST_PAGE: 4,
  ROUTE_POST_LIST_PAGE: 5,
  ROUTE_POST_LIST_TAG_PAGE: 6,
  ROUTE_HASHTAG: 7,

  ROUTE_EVENT: 'ROUTE_EVENT'
};
